<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/9_Regresion_Logistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv("Datos_limpios.csv")
df.head(5)

Unnamed: 0    host_name  host_since  host_response_time  \
0           0         Rita  26/11/2010  within a few hours   
1           1     Michelle  19/11/2012      within an hour   
2           2         Judy  27/12/2012      within an hour   
3           3         Joan  23/04/2013      within an hour   
4           4  C. F. Sandy  13/06/2013        within a day   

          property_type        room_type  bathrooms_text first_review  \
0          Entire condo  Entire home/apt          1 bath   29/12/2010   
1          Entire condo  Entire home/apt          1 bath   01/02/2013   
2  Private room in home     Private room  1 private bath   29/08/2016   
3    Entire rental unit  Entire home/apt          1 bath   02/06/2013   
4  Private room in home     Private room   1 shared bath   23/04/2017   

  last_review  host_response_rate  ...  review_scores_value  instant_bookable  \
0  30/04/2025                 1.0  ...                 4.78                 0   
1  27/07/2024                 1.0  ...                 4.76                 0   
2  30/09/2023                 1.0  ...                 4.83                 0   
3  29/10/2024                 1.0  ...                 4.66                 1   
4  09/11/2019                 1.0  ...                 4.53                 0   

   calculated_host_listings_count  \
0                             1.0   
1                             1.0   
2                             2.0   
3                             9.0   
4                             1.0   

   calculated_host_listings_count_entire_homes  \
0                                          1.0   
1                                          1.0   
2                                          0.0   
3                                          9.0   
4                                          0.0   

   calculated_host_listings_count_private_rooms  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   

   calculated_host_listings_count_shared_rooms  reviews_per_month  \
0                                          0.0               0.32   
1                                          0.0               0.46   
2                                          0.0               0.66   
3                                          0.0               0.65   
4                                          0.0               0.30   

   host_since_num  first_review_num  last_review_num  
0             417            4827.0           3433.0  
1            1141            4827.0           3521.0  
2            1179            4827.0           3521.0  
3            1296            4827.0           3521.0  
4            1347            4827.0           3521.0  

[5 rows x 53 columns]

Instant_bookable

In [3]:
# Codificar la variable categórica room_type
le = LabelEncoder()
df['room_type_encoded'] = le.fit_transform(df['room_type'])

In [4]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df[['host_response_rate', 'review_scores_value', 'room_type_encoded']]
Var_Dep= df['instant_bookable']

In [5]:
#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

In [6]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [7]:
#Se escalan todos los datos
escalar = StandardScaler()

In [8]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [9]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [10]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [11]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [12]:
# Verificar los valores únicos en y_test y y_pred
print("Valores únicos en y_test:", np.unique(y_test))
print("Valores únicos en y_pred:", np.unique(y_pred))

Valores únicos en y_test: [0 1]
Valores únicos en y_pred: [0 1]


In [20]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[959  62]
 [545 151]]


In [21]:
#Calculo la precisión del modelo Yes=1 No=0
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label=0)
print('Precisión del modelo F:')
print(precision)

Precisión del modelo F:
0.6376329787234043


In [22]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('Precisión del modelo T:')
print(precision)

Precisión del modelo T:
0.7089201877934272


In [23]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.6464764123471171


In [24]:
#Calculo la sensibilidad del modelo yes=1 No=0
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=0)
print('Sensibilidad del modelo F:')
print(sensibilidad)

Sensibilidad del modelo F:
0.9392752203721841


In [25]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo T:')
print(sensibilidad)

Sensibilidad del modelo T:
0.21695402298850575


In [26]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef1 = f1_score(y_test, y_pred, average="binary", pos_label=1)
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.33223322332233224


host_is_superhost

In [28]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep = df[['host_response_rate', 'review_scores_rating', 'review_scores_cleanliness', 
                 'review_scores_communication', 'number_of_reviews']]
Var_Dep = df['host_is_superhost']

#Redefinimos las variables 
X = Vars_Indep
y = Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [29]:
#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [30]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [31]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

# Verificar los valores únicos en y_test y y_pred
print("Valores únicos en y_test:", np.unique(y_test))
print("Valores únicos en y_pred:", np.unique(y_pred))

Valores únicos en y_test: [0 1]
Valores únicos en y_pred: [0 1]


In [32]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[714 288]
 [259 456]]


In [33]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('Precisión del modelo T:')
print(precision)

#Calculo la precisión del modelo Yes=1 No=0
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label=0)
print('Precisión del modelo F:')
print(precision)

Precisión del modelo T:
0.6129032258064516
Precisión del modelo F:
0.7338129496402878


In [34]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.6814210832847991


In [35]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo T:')
print(sensibilidad)

#Calculo la sensibilidad del modelo yes=1 No=0
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=0)
print('Sensibilidad del modelo F:')
print(sensibilidad)

Sensibilidad del modelo T:
0.6377622377622377
Sensibilidad del modelo F:
0.7125748502994012


In [36]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef1 = f1_score(y_test, y_pred, average="binary", pos_label=1)
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.6250856751199452


room_type

# Convertir room_type en variable dicotómica
Vamos a convertir room_type en dos categorías:
- "Entire home/apt" = 1
- Otros tipos (Private room, Shared room) = 0

In [49]:
# Primero veamos los valores únicos actuales
print("Valores únicos en room_type:", np.unique(df['room_type']))

# Convertimos room_type a variable dicotómica
df['room_type_binary'] = (df['room_type'] == 'Entire home/apt').astype(int)

# Verificamos la conversión
print("\nValores únicos en room_type_binary:", np.unique(df['room_type_binary']))
print("\nDistribución de room_type_binary:")
print(df['room_type_binary'].value_counts())

Valores únicos en room_type: ['Entire home/apt' 'Hotel room' 'Private room' 'Shared room']

Valores únicos en room_type_binary: [0 1]

Distribución de room_type_binary:
room_type_binary
1    4992
0     731
Name: count, dtype: int64


In [50]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep = df[['price', 'accommodates', 'bathrooms', 'bedrooms']]
Var_Dep = df['room_type_binary']

#Redefinimos las variables 
X = Vars_Indep
y = Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [51]:
#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [52]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

# Verificar los valores únicos en y_test y y_pred
print("Valores únicos en y_test:", np.unique(y_test))
print("Valores únicos en y_pred:", np.unique(y_pred))


Valores únicos en y_test: [0 1]
Valores únicos en y_pred: [0 1]


In [53]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[  69  142]
 [   5 1501]]


In [54]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('Precisión del modelo T:')
print(precision)

#Calculo la precisión del modelo Yes=1 No=0
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label=0)
print('Precisión del modelo F:')
print(precision)

Precisión del modelo T:
0.913572732805843
Precisión del modelo F:
0.9324324324324325


In [55]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.9143855562026791


In [56]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo T:')
print(sensibilidad)

#Calculo la sensibilidad del modelo yes=1 No=0
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=0)
print('Sensibilidad del modelo F:')
print(sensibilidad)

Sensibilidad del modelo T:
0.9966799468791501
Sensibilidad del modelo F:
0.32701421800947866


In [57]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef1 = f1_score(y_test, y_pred, average="binary", pos_label=1)
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.9533185138139092


host_response_time

# Convertir host_response_time en variable dicotómica
Vamos a convertir host_response_time en dos categorías:
- Respuesta rápida (within an hour) = 1
- Respuesta más lenta (más de una hora) = 0

In [82]:
# Primero veamos los valores únicos actuales
print("Valores únicos en host_response_time:", np.unique(df['host_response_time']))

# Convertimos host_response_time a variable dicotómica
df['response_time_binary'] = (df['host_response_time'] == 'within an hour').astype(int)

# Verificamos la conversión
print("\nValores únicos en response_time_binary:", np.unique(df['response_time_binary']))
print("\nDistribución de response_time_binary:")
print(df['response_time_binary'].value_counts())

Valores únicos en host_response_time: ['a few days or more' 'within a day' 'within a few hours' 'within an hour']

Valores únicos en response_time_binary: [0 1]

Distribución de response_time_binary:
response_time_binary
1    4651
0    1072
Name: count, dtype: int64


In [84]:
# Mostrar la distribución original de las clases antes del balanceo
print("Distribución de clases antes del balanceo:")
print(pd.Series(y_train).value_counts())

# Importamos SMOTE para el balanceo de datos
from imblearn.over_sampling import SMOTE

#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep = df[['host_acceptance_rate', 'host_is_superhost', 'review_scores_communication']]
Var_Dep = df['response_time_binary']

# Convertir host_acceptance_rate a numérico
# Primero reemplazamos los valores nulos con '0%'
Vars_Indep['host_acceptance_rate'] = Vars_Indep['host_acceptance_rate'].fillna('0%')
# Ahora convertimos a float
Vars_Indep['host_acceptance_rate'] = Vars_Indep['host_acceptance_rate'].apply(lambda x: float(str(x).rstrip('%')) / 100)

#Redefinimos las variables 
X = Vars_Indep
y = Var_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Aplicamos SMOTE solo a los datos de entrenamiento
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Verificamos la distribución después del balanceo
print("\nDistribución de clases después del balanceo:")
print(pd.Series(y_train_balanced).value_counts())

Distribución de clases antes del balanceo:
response_time_binary
1    3256
0     750
Name: count, dtype: int64

Distribución de clases después del balanceo:
response_time_binary
1    3256
0    3256
Name: count, dtype: int64


C:\Users\gaboo\AppData\Local\Temp\ipykernel_15348\2310242258.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Vars_Indep['host_acceptance_rate'] = Vars_Indep['host_acceptance_rate'].fillna('0%')
C:\Users\gaboo\AppData\Local\Temp\ipykernel_15348\2310242258.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Vars_Indep['host_acceptance_rate'] = Vars_Indep['host_acceptance_rate'].apply(lambda x: float(str(x).rstrip('%')) / 100)


In [85]:
#Se escalan todos los datos
escalar = StandardScaler()

#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train_balanced = escalar.fit_transform(X_train_balanced)
X_test = escalar.transform(X_test)

In [86]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

#Entrenamos el modelo con los datos balanceados
algoritmo.fit(X_train_balanced, y_train_balanced)

#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

# Verificar los valores únicos en y_test y y_pred
print("Valores únicos en y_test:", np.unique(y_test))
print("Valores únicos en y_pred:", np.unique(y_pred))

# Mostrar la distribución de las predicciones
print("\nDistribución de las predicciones:")
print(pd.Series(y_pred).value_counts())

Valores únicos en y_test: [0 1]
Valores únicos en y_pred: [0 1]

Distribución de las predicciones:
0    1002
1     715
Name: count, dtype: int64


In [87]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[269  53]
 [733 662]]


In [88]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('Precisión del modelo T:')
print(precision)

#Calculo la precisión del modelo Yes=1 No=0
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label=0)
print('Precisión del modelo F:')
print(precision)

Precisión del modelo T:
0.9258741258741259
Precisión del modelo F:
0.2684630738522954


In [89]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.5422248107163657


In [90]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print('Sensibilidad del modelo T:')
print(sensibilidad)

#Calculo la sensibilidad del modelo yes=1 No=0
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=0)
print('Sensibilidad del modelo F:')
print(sensibilidad)

Sensibilidad del modelo T:
0.4745519713261649
Sensibilidad del modelo F:
0.8354037267080745


In [91]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef1 = f1_score(y_test, y_pred, average="binary", pos_label=1)
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.6274881516587678


# Convertir availability_365 en variable dicotómica
Vamos a convertir availability_365 en dos categorías:
- Alta disponibilidad (>180 días) = 1
- Baja disponibilidad (≤180 días) = 0

In [96]:
# Primero veamos los valores únicos actuales y la distribución
print("Estadísticas de availability_365:")
print(df['availability_365'].describe())

# Convertimos availability_365 a variable dicotómica
df['availability_binary'] = (df['availability_365'] > 180).astype(int)

# Verificamos la conversión
print("\nValores únicos en availability_binary:", np.unique(df['availability_binary']))
print("\nDistribución de availability_binary:")
print(df['availability_binary'].value_counts())

Estadísticas de availability_365:
count    5723.000000
mean      253.241482
std       118.140893
min         0.000000
25%       170.000000
50%       299.000000
75%       355.000000
max       365.000000
Name: availability_365, dtype: float64

Valores únicos en availability_binary: [0 1]

Distribución de availability_binary:
availability_binary
1    4138
0    1585
Name: count, dtype: int64


In [97]:
# Preparamos los datos para el modelo de regresión logística
Vars_Indep = df[['price', 'minimum_nights', 'review_scores_rating', 'reviews_per_month']]
Var_Dep = df['availability_binary']

# Redefinimos las variables
X = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Mostramos la distribución original
print("Distribución de clases antes del balanceo:")
print(pd.Series(y_train).value_counts())

Distribución de clases antes del balanceo:
availability_binary
1    2896
0    1110
Name: count, dtype: int64


In [98]:
# Aplicamos SMOTE para balancear las clases
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Verificamos la distribución después del balanceo
print("\nDistribución de clases después del balanceo:")
print(pd.Series(y_train_balanced).value_counts())


Distribución de clases después del balanceo:
availability_binary
1    2896
0    2896
Name: count, dtype: int64


In [99]:
# Escalamos los datos
escalar = StandardScaler()
X_train_balanced = escalar.fit_transform(X_train_balanced)
X_test = escalar.transform(X_test)

# Entrenamos el modelo
algoritmo = LogisticRegression()
algoritmo.fit(X_train_balanced, y_train_balanced)

# Realizamos predicciones
y_pred = algoritmo.predict(X_test)

# Mostramos la distribución de las predicciones
print("Distribución de las predicciones:")
print(pd.Series(y_pred).value_counts())

Distribución de las predicciones:
1    894
0    823
Name: count, dtype: int64


In [100]:
# Evaluación del modelo
# Matriz de confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Precisión
precision_pos = precision_score(y_test, y_pred, pos_label=1)
precision_neg = precision_score(y_test, y_pred, pos_label=0)
print('\nPrecisión para alta disponibilidad (1):', precision_pos)
print('Precisión para baja disponibilidad (0):', precision_neg)

# Sensibilidad (Recall)
recall_pos = recall_score(y_test, y_pred, pos_label=1)
recall_neg = recall_score(y_test, y_pred, pos_label=0)
print('\nSensibilidad para alta disponibilidad (1):', recall_pos)
print('Sensibilidad para baja disponibilidad (0):', recall_neg)

# Exactitud
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:', exactitud)

# F1 Score
f1 = f1_score(y_test, y_pred, pos_label=1)
print('\nPuntaje F1:', f1)

Matriz de Confusión:
[[266 209]
 [557 685]]

Precisión para alta disponibilidad (1): 0.7662192393736018
Precisión para baja disponibilidad (0): 0.32320777642770354

Sensibilidad para alta disponibilidad (1): 0.5515297906602254
Sensibilidad para baja disponibilidad (0): 0.56

Exactitud del modelo: 0.5538730343622598

Puntaje F1: 0.6413857677902621


# Convertir property_type en variable dicotómica
Vamos a convertir property_type en dos categorías:
- "Apartment/Condo" (Apartamentos y Condominios) = 1
- Otros tipos de propiedades = 0

In [110]:
# Primero veamos los valores únicos actuales
print("Valores únicos en property_type:")
print(df['property_type'].value_counts())

# Convertimos property_type a variable dicotómica
df['property_type_binary'] = df['property_type'].str.contains('Apartment|Condo|Condominium|Loft', case=False).astype(int)

# Verificamos la conversión
print("\nValores únicos en property_type_binary:", np.unique(df['property_type_binary']))
print("\nDistribución de property_type_binary:")
print(df['property_type_binary'].value_counts(dropna=False))

Valores únicos en property_type:
property_type
Entire rental unit                    2273
Entire home                           1655
Private room in home                   453
Entire condo                           359
Entire townhouse                       235
Entire guesthouse                      162
Room in hotel                          160
Private room in rental unit             59
Entire loft                             56
Entire serviced apartment               46
Entire guest suite                      38
Private room in townhouse               35
Shared room in home                     27
Entire bungalow                         23
Tiny home                               23
Private room in condo                   21
Room in boutique hotel                  19
Entire villa                            15
Private room in serviced apartment      10
Camper/RV                                9
Entire cottage                           8
Shipping container                       5
Private

In [111]:
# Preparamos los datos para el modelo de regresión logística
Vars_Indep = df[['price', 'bedrooms', 'bathrooms', 'review_scores_rating', 'review_scores_location']]
Var_Dep = df['property_type_binary']

# Manejamos los valores nulos en las variables independientes
Vars_Indep = Vars_Indep.fillna(Vars_Indep.mean())

# Redefinimos las variables
X = Vars_Indep
y = Var_Dep

# Eliminamos las filas donde y es nulo
mask = ~y.isnull()
X = X[mask]
y = y[mask]

# Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Mostramos la distribución original
print("Distribución de clases antes del balanceo:")
print(pd.Series(y_train).value_counts())

Distribución de clases antes del balanceo:
property_type_binary
0    3686
1     320
Name: count, dtype: int64


In [112]:
# Verificamos los valores únicos y la distribución en los datos originales
print("Valores únicos en property_type_binary en todos los datos:")
print(df['property_type_binary'].unique())
print("\nDistribución en todos los datos:")
print(df['property_type_binary'].value_counts(dropna=False))

# Verificamos si hay valores nulos
print("\nCantidad de valores nulos:")
print(df['property_type_binary'].isnull().sum())

# Verificamos los valores en X
print("\nVerificamos los datos en las variables independientes:")
print("Valores nulos en X:")
print(Vars_Indep.isnull().sum())

Valores únicos en property_type_binary en todos los datos:
[1 0]

Distribución en todos los datos:
property_type_binary
0    5229
1     494
Name: count, dtype: int64

Cantidad de valores nulos:
0

Verificamos los datos en las variables independientes:
Valores nulos en X:
price                     0
bedrooms                  0
bathrooms                 0
review_scores_rating      0
review_scores_location    0
dtype: int64


In [113]:
# Verificamos que tenemos al menos dos clases antes de aplicar SMOTE
unique_classes = len(np.unique(y_train))
print(f"Número de clases únicas en y_train: {unique_classes}")
print("Valores únicos:", np.unique(y_train))

if unique_classes > 1:
    # Aplicamos SMOTE para balancear las clases
    smote = SMOTE(random_state=42)
    X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)
    
    # Verificamos la distribución después del balanceo
    print("\nDistribución de clases después del balanceo:")
    print(pd.Series(y_train_balanced).value_counts())
else:
    print("\n¡ADVERTENCIA! Solo hay una clase en los datos de entrenamiento.")
    print("No se puede aplicar SMOTE. Usando los datos sin balancear.")
    X_train_balanced, y_train_balanced = X_train, y_train

Número de clases únicas en y_train: 2
Valores únicos: [0 1]

Distribución de clases después del balanceo:
property_type_binary
0    3686
1    3686
Name: count, dtype: int64


In [114]:
# Escalamos los datos
escalar = StandardScaler()
X_train_balanced = escalar.fit_transform(X_train_balanced)
X_test = escalar.transform(X_test)

# Entrenamos el modelo
algoritmo = LogisticRegression()
algoritmo.fit(X_train_balanced, y_train_balanced)

# Realizamos predicciones
y_pred = algoritmo.predict(X_test)

# Mostramos la distribución de las predicciones
print("Distribución de las predicciones:")
print(pd.Series(y_pred).value_counts())

Distribución de las predicciones:
1    891
0    826
Name: count, dtype: int64


In [115]:
# Evaluación del modelo
# Matriz de confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Precisión
precision_pos = precision_score(y_test, y_pred, pos_label=1)
precision_neg = precision_score(y_test, y_pred, pos_label=0)
print('\nPrecisión para Apartment/Condo (1):', precision_pos)
print('Precisión para otros tipos (0):', precision_neg)

# Sensibilidad (Recall)
recall_pos = recall_score(y_test, y_pred, pos_label=1)
recall_neg = recall_score(y_test, y_pred, pos_label=0)
print('\nSensibilidad para Apartment/Condo (1):', recall_pos)
print('Sensibilidad para otros tipos (0):', recall_neg)

# Exactitud
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:', exactitud)

# F1 Score
f1 = f1_score(y_test, y_pred, pos_label=1)
print('\nPuntaje F1:', f1)

Matriz de Confusión:
[[774 769]
 [ 52 122]]

Precisión para Apartment/Condo (1): 0.13692480359147025
Precisión para otros tipos (0): 0.937046004842615

Sensibilidad para Apartment/Condo (1): 0.7011494252873564
Sensibilidad para otros tipos (0): 0.5016202203499676

Exactitud del modelo: 0.5218404193360513

Puntaje F1: 0.2291079812206573


# Convertir host_response_rate en variable dicotómica
Vamos a convertir host_response_rate en dos categorías:
- Alta tasa de respuesta (≥90%) = 1
- Baja tasa de respuesta (<90%) = 0

In [123]:
# Primero veamos los valores únicos actuales y su distribución
print("Distribución de host_response_rate original:")
print(df['host_response_rate'].value_counts().sort_index())

# Convertimos host_response_rate a numérico
# Primero reemplazamos los valores nulos con '0%'
df['host_response_rate_clean'] = df['host_response_rate'].fillna('0%')
# Convertimos a float (asumiendo que los valores ya están en decimal)
df['host_response_rate_clean'] = df['host_response_rate_clean'].apply(lambda x: float(str(x)))

# Analizamos la distribución de los valores numéricos
print("\nEstadísticas de host_response_rate_clean:")
print(df['host_response_rate_clean'].describe())

# Convertimos a binario (1 para ≥98%, 0 para <98%)
df['response_rate_binary'] = (df['host_response_rate_clean'] >= 0.98).astype(int)

# Verificamos la conversión
print("\nValores únicos en response_rate_binary:", np.unique(df['response_rate_binary']))
print("\nDistribución de response_rate_binary:")
print(df['response_rate_binary'].value_counts())

Distribución de host_response_rate original:
host_response_rate
0.95      86
0.96     139
0.97      62
0.98     176
0.99     273
1.00    4987
Name: count, dtype: int64

Estadísticas de host_response_rate_clean:
count    5723.000000
mean        0.996860
std         0.009665
min         0.950000
25%         1.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: host_response_rate_clean, dtype: float64

Valores únicos en response_rate_binary: [0 1]

Distribución de response_rate_binary:
response_rate_binary
1    5436
0     287
Name: count, dtype: int64


In [124]:
# Preparamos los datos para el modelo de regresión logística
Vars_Indep = df[['review_scores_communication', 'review_scores_accuracy', 'number_of_reviews', 'host_is_superhost']]
Var_Dep = df['response_rate_binary']

# Redefinimos las variables
X = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Mostramos la distribución original
print("Distribución de clases antes del balanceo:")
print(pd.Series(y_train).value_counts())

Distribución de clases antes del balanceo:
response_rate_binary
1    3782
0     224
Name: count, dtype: int64


In [125]:
# Verificamos la distribución de los datos originales y los valores nulos
print("Distribución original de response_rate_binary:")
print(df['response_rate_binary'].value_counts(dropna=False))
print("\nCantidad de valores nulos:")
print(df['response_rate_binary'].isnull().sum())

# Si hay valores nulos, los eliminamos
if df['response_rate_binary'].isnull().any():
    mask = ~df['response_rate_binary'].isnull()
    Vars_Indep = Vars_Indep[mask]
    Var_Dep = df['response_rate_binary'][mask]
    print("\nDistribución después de eliminar nulos:")
    print(Var_Dep.value_counts())

Distribución original de response_rate_binary:
response_rate_binary
1    5436
0     287
Name: count, dtype: int64

Cantidad de valores nulos:
0


In [126]:
# Verificamos que tenemos al menos dos clases antes de aplicar SMOTE
unique_classes = len(np.unique(y_train))
print(f"Número de clases únicas en y_train: {unique_classes}")
print("Valores únicos:", np.unique(y_train))

if unique_classes > 1:
    # Aplicamos SMOTE para balancear las clases
    smote = SMOTE(random_state=42)
    X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)
    
    # Verificamos la distribución después del balanceo
    print("\nDistribución de clases después del balanceo:")
    print(pd.Series(y_train_balanced).value_counts())
else:
    print("\n¡ADVERTENCIA! Solo hay una clase en los datos de entrenamiento.")
    print("No se puede aplicar SMOTE. Usando los datos sin balancear.")
    X_train_balanced, y_train_balanced = X_train, y_train

Número de clases únicas en y_train: 2
Valores únicos: [0 1]

Distribución de clases después del balanceo:
response_rate_binary
1    3782
0    3782
Name: count, dtype: int64


In [127]:
# Escalamos los datos
escalar = StandardScaler()
X_train_balanced = escalar.fit_transform(X_train_balanced)
X_test = escalar.transform(X_test)

# Entrenamos el modelo
algoritmo = LogisticRegression()
algoritmo.fit(X_train_balanced, y_train_balanced)

# Realizamos predicciones
y_pred = algoritmo.predict(X_test)

# Mostramos la distribución de las predicciones
print("Distribución de las predicciones:")
print(pd.Series(y_pred).value_counts())

Distribución de las predicciones:
1    899
0    818
Name: count, dtype: int64


In [128]:
# Evaluación del modelo
# Matriz de confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Precisión
precision_pos = precision_score(y_test, y_pred, pos_label=1)
precision_neg = precision_score(y_test, y_pred, pos_label=0)
print('\nPrecisión para alta tasa de respuesta (1):', precision_pos)
print('Precisión para baja tasa de respuesta (0):', precision_neg)

# Sensibilidad (Recall)
recall_pos = recall_score(y_test, y_pred, pos_label=1)
recall_neg = recall_score(y_test, y_pred, pos_label=0)
print('\nSensibilidad para alta tasa de respuesta (1):', recall_pos)
print('Sensibilidad para baja tasa de respuesta (0):', recall_neg)

# Exactitud
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:', exactitud)

# F1 Score
f1 = f1_score(y_test, y_pred, pos_label=1)
print('\nPuntaje F1:', f1)

Matriz de Confusión:
[[ 56   7]
 [762 892]]

Precisión para alta tasa de respuesta (1): 0.9922135706340378
Precisión para baja tasa de respuesta (0): 0.06845965770171149

Sensibilidad para alta tasa de respuesta (1): 0.5392986698911729
Sensibilidad para baja tasa de respuesta (0): 0.8888888888888888

Exactitud del modelo: 0.5521258008153757

Puntaje F1: 0.6987857422640031


# Convertir host_acceptance_rate en variable dicotómica
Vamos a convertir host_acceptance_rate en dos categorías:
- Alta tasa de aceptación (≥85%) = 1
- Baja tasa de aceptación (<85%) = 0

In [131]:
# Primero veamos los valores únicos actuales y su distribución
print("Distribución de host_acceptance_rate original:")
print(df['host_acceptance_rate'].value_counts().sort_index())

# Convertimos host_acceptance_rate a numérico
# Primero reemplazamos los valores nulos con '0%'
df['host_acceptance_rate_clean'] = df['host_acceptance_rate'].fillna('0%')
# Convertimos a float
df['host_acceptance_rate_clean'] = df['host_acceptance_rate_clean'].apply(lambda x: float(str(x).rstrip('%')) / 100)

# Analizamos la distribución de los valores numéricos
print("\nEstadísticas de host_acceptance_rate_clean:")
print(df['host_acceptance_rate_clean'].describe())

# Mostramos los percentiles para ayudar a elegir un mejor umbral
print("\nPercentiles de host_acceptance_rate_clean:")
percentiles = [25, 50, 75]
for p in percentiles:
    print(f"Percentil {p}: {df['host_acceptance_rate_clean'].quantile(p/100):.2f}")

# Convertimos a binario usando el percentil 50 como umbral
umbral = df['host_acceptance_rate_clean'].median()
print(f"\nUsando umbral de {umbral:.2f} (mediana)")
df['acceptance_rate_binary'] = (df['host_acceptance_rate_clean'] >= umbral).astype(int)

# Verificamos la conversión
print("\nValores únicos en acceptance_rate_binary:", np.unique(df['acceptance_rate_binary']))
print("\nDistribución de acceptance_rate_binary:")
print(df['acceptance_rate_binary'].value_counts())

Distribución de host_acceptance_rate original:
host_acceptance_rate
0.70      16
0.71       6
0.72       3
0.73      18
0.74      23
0.75      50
0.76       9
0.77      15
0.78      42
0.79      32
0.80      56
0.81      31
0.82      45
0.83      47
0.84      15
0.85      18
0.86     104
0.87      31
0.88     100
0.89      54
0.90      44
0.91      72
0.92      58
0.93      63
0.94     118
0.95     252
0.96     230
0.97     150
0.98     309
0.99     876
1.00    2836
Name: count, dtype: int64

Estadísticas de host_acceptance_rate_clean:
count    5723.000000
mean        0.009659
std         0.000611
min         0.007000
25%         0.009600
50%         0.009900
75%         0.010000
max         0.010000
Name: host_acceptance_rate_clean, dtype: float64

Percentiles de host_acceptance_rate_clean:
Percentil 25: 0.01
Percentil 50: 0.01
Percentil 75: 0.01

Usando umbral de 0.01 (mediana)

Valores únicos en acceptance_rate_binary: [0 1]

Distribución de acceptance_rate_binary:
acceptance_rate_b

In [132]:
# Preparamos los datos para el modelo de regresión logística
Vars_Indep = df[['review_scores_communication', 'host_response_rate', 'number_of_reviews', 'review_scores_rating']]
Var_Dep = df['acceptance_rate_binary']

# Manejamos los valores nulos en las variables independientes
Vars_Indep = Vars_Indep.fillna(Vars_Indep.mean())

# Redefinimos las variables
X = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Mostramos la distribución original
print("Distribución de clases antes del balanceo:")
print(pd.Series(y_train).value_counts())

Distribución de clases antes del balanceo:
acceptance_rate_binary
1    2596
0    1410
Name: count, dtype: int64


In [133]:
# Aplicamos SMOTE para balancear las clases
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Verificamos la distribución después del balanceo
print("\nDistribución de clases después del balanceo:")
print(pd.Series(y_train_balanced).value_counts())


Distribución de clases después del balanceo:
acceptance_rate_binary
0    2596
1    2596
Name: count, dtype: int64


In [134]:
# Escalamos los datos
escalar = StandardScaler()
X_train_balanced = escalar.fit_transform(X_train_balanced)
X_test = escalar.transform(X_test)

# Entrenamos el modelo
algoritmo = LogisticRegression()
algoritmo.fit(X_train_balanced, y_train_balanced)

# Realizamos predicciones
y_pred = algoritmo.predict(X_test)

# Mostramos la distribución de las predicciones
print("Distribución de las predicciones:")
print(pd.Series(y_pred).value_counts())

Distribución de las predicciones:
1    1419
0     298
Name: count, dtype: int64


In [135]:
# Evaluación del modelo
# Matriz de confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Precisión
precision_pos = precision_score(y_test, y_pred, pos_label=1)
precision_neg = precision_score(y_test, y_pred, pos_label=0)
print('\nPrecisión para alta tasa de aceptación (1):', precision_pos)
print('Precisión para baja tasa de aceptación (0):', precision_neg)

# Sensibilidad (Recall)
recall_pos = recall_score(y_test, y_pred, pos_label=1)
recall_neg = recall_score(y_test, y_pred, pos_label=0)
print('\nSensibilidad para alta tasa de aceptación (1):', recall_pos)
print('Sensibilidad para baja tasa de aceptación (0):', recall_neg)

# Exactitud
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:', exactitud)

# F1 Score
f1 = f1_score(y_test, y_pred, pos_label=1)
print('\nPuntaje F1:', f1)

Matriz de Confusión:
[[114 487]
 [184 932]]

Precisión para alta tasa de aceptación (1): 0.656800563777308
Precisión para baja tasa de aceptación (0): 0.3825503355704698

Sensibilidad para alta tasa de aceptación (1): 0.8351254480286738
Sensibilidad para baja tasa de aceptación (0): 0.1896838602329451

Exactitud del modelo: 0.6092020966802563

Puntaje F1: 0.7353057199211045


# Convertir price en variable dicotómica
Vamos a convertir price en dos categorías usando la mediana como punto de corte:
- Precio alto (≥ mediana) = 1
- Precio bajo (< mediana) = 0

In [136]:
# Primero veamos la distribución actual y estadísticas de price
print("Estadísticas de price:")
print(df['price'].describe())

# Mostramos los percentiles para entender mejor la distribución
print("\nPercentiles de price:")
percentiles = [25, 50, 75]
for p in percentiles:
    print(f"Percentil {p}: ${df['price'].quantile(p/100):.2f}")

# Usamos la mediana como punto de corte
umbral = df['price'].median()
print(f"\nUsando umbral de ${umbral:.2f} (mediana)")

# Convertimos a binario
df['price_binary'] = (df['price'] >= umbral).astype(int)

# Verificamos la conversión
print("\nValores únicos en price_binary:", np.unique(df['price_binary']))
print("\nDistribución de price_binary:")
print(df['price_binary'].value_counts())

Estadísticas de price:
count    5723.000000
mean      123.189411
std        66.039277
min        11.000000
25%        80.000000
50%       105.000000
75%       147.000000
max       382.000000
Name: price, dtype: float64

Percentiles de price:
Percentil 25: $80.00
Percentil 50: $105.00
Percentil 75: $147.00

Usando umbral de $105.00 (mediana)

Valores únicos en price_binary: [0 1]

Distribución de price_binary:
price_binary
1    3230
0    2493
Name: count, dtype: int64


In [137]:
# Preparamos los datos para el modelo de regresión logística
Vars_Indep = df[['room_type_encoded', 'accommodates', 'bathrooms', 'bedrooms', 'review_scores_rating']]
Var_Dep = df['price_binary']

# Manejamos los valores nulos en las variables independientes
Vars_Indep = Vars_Indep.fillna(Vars_Indep.mean())

# Redefinimos las variables
X = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Mostramos la distribución original
print("Distribución de clases antes del balanceo:")
print(pd.Series(y_train).value_counts())

Distribución de clases antes del balanceo:
price_binary
1    2270
0    1736
Name: count, dtype: int64


In [138]:
# Aplicamos SMOTE para balancear las clases
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Verificamos la distribución después del balanceo
print("\nDistribución de clases después del balanceo:")
print(pd.Series(y_train_balanced).value_counts())


Distribución de clases después del balanceo:
price_binary
1    2270
0    2270
Name: count, dtype: int64


In [139]:
# Escalamos los datos
escalar = StandardScaler()
X_train_balanced = escalar.fit_transform(X_train_balanced)
X_test = escalar.transform(X_test)

# Entrenamos el modelo
algoritmo = LogisticRegression()
algoritmo.fit(X_train_balanced, y_train_balanced)

# Realizamos predicciones
y_pred = algoritmo.predict(X_test)

# Mostramos la distribución de las predicciones
print("Distribución de las predicciones:")
print(pd.Series(y_pred).value_counts())

Distribución de las predicciones:
0    976
1    741
Name: count, dtype: int64


In [140]:
# Evaluación del modelo
# Matriz de confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Precisión
precision_pos = precision_score(y_test, y_pred, pos_label=1)
precision_neg = precision_score(y_test, y_pred, pos_label=0)
print('\nPrecisión para precio alto (1):', precision_pos)
print('Precisión para precio bajo (0):', precision_neg)

# Sensibilidad (Recall)
recall_pos = recall_score(y_test, y_pred, pos_label=1)
recall_neg = recall_score(y_test, y_pred, pos_label=0)
print('\nSensibilidad para precio alto (1):', recall_pos)
print('Sensibilidad para precio bajo (0):', recall_neg)

# Exactitud
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:', exactitud)

# F1 Score
f1 = f1_score(y_test, y_pred, pos_label=1)
print('\nPuntaje F1:', f1)

Matriz de Confusión:
[[654 103]
 [322 638]]

Precisión para precio alto (1): 0.8609986504723347
Precisión para precio bajo (0): 0.6700819672131147

Sensibilidad para precio alto (1): 0.6645833333333333
Sensibilidad para precio bajo (0): 0.8639365918097754

Exactitud del modelo: 0.7524752475247525

Puntaje F1: 0.7501469723691946


# Convertir review_scores_rating en variable dicotómica

Vamos a convertir la variable review_scores_rating en una variable dicotómica usando un umbral de 4.5:
* 1 = Calificación alta (≥ 4.5)
* 0 = Calificación baja (< 4.5)

In [160]:
# Primero veamos la distribución actual y estadísticas
print("Estadísticas de review_scores_rating:")
print(df['review_scores_rating'].describe())

# Mostramos los percentiles para entender mejor la distribución
print("\nPercentiles de review_scores_rating:")
percentiles = [25, 50, 75, 90]
for p in percentiles:
    print(f"Percentil {p}: {df['review_scores_rating'].quantile(p/100):.2f}")

# Convertimos a binario usando 4.5 como umbral (calificaciones de 4.5 o más son consideradas altas)
umbral = 4.5
print(f"\nUsando umbral de {umbral:.1f}")

# Convertimos a binario
df['rating_binary'] = (df['review_scores_rating'] >= umbral).astype(int)

# Verificamos la conversión
print("\nValores únicos en rating_binary:", np.unique(df['rating_binary']))
print("\nDistribución de rating_binary:")
print(df['rating_binary'].value_counts())

Estadísticas de review_scores_rating:
count    5723.000000
mean        4.816663
std         0.156250
min         4.300000
25%         4.700000
50%         4.820000
75%         4.970000
max         5.000000
Name: review_scores_rating, dtype: float64

Percentiles de review_scores_rating:
Percentil 25: 4.70
Percentil 50: 4.82
Percentil 75: 4.97
Percentil 90: 5.00

Usando umbral de 4.5

Valores únicos en rating_binary: [0 1]

Distribución de rating_binary:
rating_binary
1    5539
0     184
Name: count, dtype: int64


In [161]:
# Preparamos los datos para el modelo de regresión logística
Vars_Indep = df[['room_type_encoded', 'accommodates', 'bathrooms', 'bedrooms', 'price']]
Var_Dep = df['rating_binary']

# Manejamos los valores nulos en las variables independientes
Vars_Indep = Vars_Indep.fillna(Vars_Indep.mean())

# Redefinimos las variables
X = Vars_Indep
y = Var_Dep

# Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Aplicamos SMOTE para balancear las clases
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Mostramos la distribución original y después de SMOTE
print("Distribución de clases antes del balanceo:")
print(pd.Series(y_train).value_counts())
print("\nDistribución de clases después de SMOTE:")
print(pd.Series(y_train_balanced).value_counts())

Distribución de clases antes del balanceo:
rating_binary
1    3874
0     132
Name: count, dtype: int64

Distribución de clases después de SMOTE:
rating_binary
1    3874
0    3874
Name: count, dtype: int64


In [162]:
# Escalamos los datos
escalar = StandardScaler()
X_train_balanced = escalar.fit_transform(X_train_balanced)
X_test = escalar.transform(X_test)

# Entrenamos el modelo
algoritmo = LogisticRegression()
algoritmo.fit(X_train_balanced, y_train_balanced)

# Realizamos predicciones
y_pred = algoritmo.predict(X_test)

# Mostramos la distribución de las predicciones
print("Distribución de las predicciones:")
print(pd.Series(y_pred).value_counts())


Distribución de las predicciones:
0    910
1    807
Name: count, dtype: int64


In [163]:
# Evaluación del modelo
# Matriz de confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

# Precisión
precision_pos = precision_score(y_test, y_pred, pos_label=1)
precision_neg = precision_score(y_test, y_pred, pos_label=0)
print('\nPrecisión para calificación alta (1):', precision_pos)
print('Precisión para calificación baja (0):', precision_neg)

# Sensibilidad (Recall)
recall_pos = recall_score(y_test, y_pred, pos_label=1)
recall_neg = recall_score(y_test, y_pred, pos_label=0)
print('\nSensibilidad para calificación alta (1):', recall_pos)
print('Sensibilidad para calificación baja (0):', recall_neg)

# Exactitud
exactitud = accuracy_score(y_test, y_pred)
print('\nExactitud del modelo:', exactitud)

# F1 Score
f1 = f1_score(y_test, y_pred, pos_label=1)
print('\nPuntaje F1:', f1)

Matriz de Confusión:
[[ 37  15]
 [873 792]]

Precisión para calificación alta (1): 0.9814126394052045
Precisión para calificación baja (0): 0.04065934065934066

Sensibilidad para calificación alta (1): 0.4756756756756757
Sensibilidad para calificación baja (0): 0.7115384615384616

Exactitud del modelo: 0.48281887012230634

Puntaje F1: 0.6407766990291263
